## 2.4 Model Selection 소개
### 학습/테스트 데이터 셋 분리 – train_test_split()

In [1]:
# 붓꽃 데이터 로드를 위한 함수, 의사결정나무 모델, 정확도 평가 함수를 불러온다.
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 붓꽃 데이터를 불러온다.
iris = load_iris()

# 의사결정나무 분류 모델 객체를 생성한다.
dt_clf = DecisionTreeClassifier()

# 붓꽃 데이터의 feature와 label을 각각 변수에 저장한다.
train_data = iris.data
train_label = iris.target

# 전체 데이터를 이용하여 모델을 학습시킨다.
dt_clf.fit(train_data, train_label)

# 학습에 사용한 같은 데이터로 다시 예측을 수행한다.
pred = dt_clf.predict(train_data)

# 실제 정답과 예측값을 비교하여 정확도를 출력한다.
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0

In [2]:
# 필요한 라이브러리를 다시 불러온다.
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# 의사결정나무 분류 모델 객체를 생성한다.
dt_clf = DecisionTreeClassifier()

# 붓꽃 데이터를 불러온다.
iris_data = load_iris()

# 전체 데이터를 학습용 데이터와 테스트용 데이터로 분리한다.
# test_size=0.3은 전체 데이터의 30%를 테스트용으로 사용한다는 뜻이다.
# random_state=121은 실행할 때마다 같은 방식으로 분리되도록 고정하는 값이다.
X_train, X_test, y_train, y_test = train_test_split(
    iris_data.data, iris_data.target, test_size=0.3, random_state=121
)

In [3]:
# 학습용 데이터를 사용하여 모델을 학습시킨다.
dt_clf.fit(X_train, y_train)

# 테스트용 데이터에 대해 예측을 수행한다.
pred = dt_clf.predict(X_test)

# 실제 테스트 정답과 예측 결과를 비교하여 정확도를 출력한다.
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556

### 교차 검증
* K 폴드

In [4]:
# 의사결정나무 모델, 정확도 평가 함수, KFold, numpy를 불러온다.
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

# 붓꽃 데이터를 불러온다.
iris = load_iris()

# feature 데이터와 label 데이터를 각각 저장한다.
features = iris.data
label = iris.target

# 의사결정나무 분류 모델 객체를 생성한다.
dt_clf = DecisionTreeClassifier(random_state=156)

# 데이터를 5개의 폴드(fold)로 나누는 KFold 객체를 생성한다.
kfold = KFold(n_splits=5)

# 각 폴드의 정확도를 저장할 리스트를 생성한다.
cv_accuracy = []

# 전체 붓꽃 데이터 개수를 출력한다.
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150

In [5]:
# 반복 횟수를 저장할 변수를 0으로 초기화한다.
n_iter = 0

# KFold의 split()을 사용하여 각 폴드별 학습/검증 인덱스를 가져온다.
for train_index, test_index in kfold.split(features):

    # 인덱스를 이용해 학습용 데이터와 검증용 데이터를 나눈다.
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 모델을 학습시키고 예측을 수행한다.
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    # 현재 반복 횟수를 1 증가시킨다.
    n_iter += 1

    # 정확도를 계산하고 소수점 넷째 자리까지 반올림한다.
    accuracy = np.round(accuracy_score(y_test, pred), 4)

    # 학습 데이터와 검증 데이터의 크기를 구한다.
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    # 각 교차 검증별 정확도와 데이터 크기를 출력한다.
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))

    # 각 검증 세트의 인덱스를 출력한다.
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))

    # 계산한 정확도를 리스트에 저장한다.
    cv_accuracy.append(accuracy)

# 전체 교차 검증 정확도의 평균을 출력한다.
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))

#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9

* Stratified K 폴드

In [6]:
# 데이터프레임 생성을 위해 pandas를 불러온다.
import pandas as pd

# 붓꽃 데이터를 불러온다.
iris = load_iris()

# feature 데이터를 DataFrame으로 변환한다.
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# label 열을 추가한다.
iris_df['label'] = iris.target

# 각 품종(label)별 데이터 개수를 확인한다.
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [7]:
# 일반 KFold 방식으로 3개의 폴드로 나눈다.
kfold = KFold(n_splits=3)

# 반복 횟수를 저장할 변수를 초기화한다.
n_iter = 0

# KFold로 분리한 각 학습/검증 데이터의 레이블 분포를 확인한다.
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1

    # 학습용과 검증용 label 데이터를 추출한다.
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]

    # 각 교차 검증별 label 분포를 출력한다.
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64

In [8]:
# StratifiedKFold를 불러온다.
from sklearn.model_selection import StratifiedKFold

# label 비율을 유지하면서 3개의 폴드로 나누는 객체를 생성한다.
skf = StratifiedKFold(n_splits=3)

# 반복 횟수를 초기화한다.
n_iter = 0

# StratifiedKFold로 분리한 각 학습/검증 데이터의 레이블 분포를 확인한다.
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1

    # 학습용과 검증용 label 데이터를 추출한다.
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]

    # 각 교차 검증별 label 분포를 출력한다.
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64

In [9]:
# 의사결정나무 모델 객체를 생성한다.
dt_clf = DecisionTreeClassifier(random_state=156)

# StratifiedKFold 객체를 생성한다.
skfold = StratifiedKFold(n_splits=3)

# 반복 횟수와 정확도 저장 리스트를 초기화한다.
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 split()을 사용하여 학습/검증 데이터를 나눈다.
for train_index, test_index in skfold.split(features, label):

    # 인덱스를 이용하여 학습용 데이터와 검증용 데이터를 추출한다.
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 모델을 학습시키고 예측을 수행한다.
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    # 반복 횟수를 증가시킨다.
    n_iter += 1

    # 정확도를 계산한다.
    accuracy = np.round(accuracy_score(y_test, pred), 4)

    # 학습 데이터와 검증 데이터 크기를 구한다.
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    # 각 교차 검증의 정확도와 데이터 크기를 출력한다.
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))

    # 검증 세트 인덱스를 출력한다.
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))

    # 정확도를 리스트에 저장한다.
    cv_accuracy.append(accuracy)

# 교차 검증별 정확도와 평균 정확도를 출력한다.
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))

#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9667

* cross_val_score( )

In [10]:
# 의사결정나무 모델, 교차 검증 함수, 붓꽃 데이터 로드 함수를 불러온다.
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

# 붓꽃 데이터를 불러온다.
iris_data = load_iris()

# 의사결정나무 모델 객체를 생성한다.
dt_clf = DecisionTreeClassifier(random_state=156)

# feature 데이터와 label 데이터를 각각 저장한다.
data = iris_data.data
label = iris_data.target

# 정확도를 기준으로 3개의 교차 검증 세트에 대해 평가를 수행한다.
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)

# 각 교차 검증별 정확도와 평균 정확도를 출력한다.
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667

* GridSearchCV

In [11]:
# 붓꽃 데이터 로드 함수, 의사결정나무 모델, GridSearchCV를 불러온다.
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 붓꽃 데이터를 불러온다.
iris = load_iris()

# 학습 데이터와 테스트 데이터를 분리한다.
X_train, X_test, y_train, y_test = train_test_split(
    iris_data.data, iris_data.target, test_size=0.2, random_state=121
)

# 의사결정나무 모델 객체를 생성한다.
dtree = DecisionTreeClassifier()

# 탐색할 하이퍼파라미터를 딕셔너리 형태로 설정한다.
parameters = {'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [12]:
# 결과를 데이터프레임으로 확인하기 위해 pandas를 불러온다.
import pandas as pd

# GridSearchCV 객체를 생성한다.
# cv=3은 3개의 교차 검증 세트로 평가한다는 뜻이다.
# refit=True는 가장 좋은 파라미터로 다시 모델을 학습시킨다는 뜻이다.
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 학습용 데이터로 GridSearchCV를 수행한다.
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 DataFrame으로 변환한다.
scores_df = pd.DataFrame(grid_dtree.cv_results_)

# 주요 결과만 확인한다.
scores_df[['params', 'mean_test_score', 'rank_test_score',
           'split0_test_score', 'split1_test_score', 'split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95

In [13]:
# 최적의 하이퍼파라미터와 최고 정확도를 출력한다.
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9750

In [14]:
# GridSearchCV에서 가장 좋은 파라미터로 이미 학습된 모델을 가져온다.
estimator = grid_dtree.best_estimator_

# 테스트 데이터에 대해 예측을 수행한다.
pred = estimator.predict(X_test)

# 테스트 데이터에 대한 정확도를 출력한다.
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667